[kbs_kstar_movie]
title = "KBS연예 ─ 영화"
url = "https://kstar.kbs.co.kr/list.html?cate=MV"
entrySelector = "ul.slice-grid3 li"
titleSelector = "span.max-progtit"
linkSelector = "a"
imageSelector = "span.img-thum span.img-center img"
waitForSelector = ".slice-grid3"
onFail = "stale"

[kbs_kstar_tv]
title = "KBS연예 ─ TVs"
url = "https://kstar.kbs.co.kr/list.html?cate=TV"
entrySelector = "ul.slice-grid3 li"
titleSelector = "span.max-progtit"
linkSelector = "a"
imageSelector = "span.img-thum span.img-center img"
waitForSelector = ".slice-grid3"
onFail = "stale"

[kbs_kstar_kbs]
title = "KBS연예 ─ KBS"
url = "https://kstar.kbs.co.kr/list.html?cate=BC"
entrySelector = "ul.slice-grid3 li"
titleSelector = "span.max-progtit"
linkSelector = "a"
imageSelector = "span.img-thum span.img-center img"
waitForSelector = ".slice-grid3"
onFail = "stale"

[mbc_enews_movie]
title = "MBC 연예 ─ 영화"
url = "http://enews.imbc.com/Search?searchText=%EC%98%81%ED%99%94"
entrySelector = "ul.news-list.list-square.list-latest li"
titleSelector = "p.summary"
linkSelector = "a"
imageSelector = "a img"
waitUntil = "networkidle"

[naver_entertain_movie]
title = "네이버TV연예 ─ 영화"
url = "https://entertain.naver.com/movie"
entrySelector = "ul[class='news_lst news_lst2'] li"
titleSelector = "div[class='tit_area'] a[class='tit']"
linkSelector = "div[class='tit_area'] a[class='tit']"
imageSelector = "li a[class='thumb_area'] img"
contentSelector = "div[class='tit_area'] p[class='summary']"

[naver_entertain_now_broadcast]
title = "네이버 TV연예 ─ 최신뉴스 ─ 방송"
url = "https://entertain.naver.com/now?sid=224"
entrySelector = "ul.news_lst.news_lst2 li"
titleSelector = "a.tit"
linkSelector = "a"
contentSelector = "p.summary"
waitUntil = "networkidle"

[naver_entertain_now_drama]
title = "네이버 TV연예 ─ 최신뉴스 ─ 드라마"
url = "https://entertain.naver.com/now?sid=225"
entrySelector = "ul.news_lst.news_lst2 li"
titleSelector = "a.tit"
linkSelector = "a"
contentSelector = "p.summary"
waitUntil = "networkidle"

[daummovie_news_popular]
title = "다음영화 뉴스 ─ 인기"
url = "https://movie.daum.net/contents/news?type=popular"
entrySelector = "div.box_movienews > ol > li"
titleSelector = "strong a[class='link_txt']"
linkSelector = "strong a[class='link_txt']"
imageSelector = "span[class='bg_img']"
contentSelector = "p[class='desc_thumb'] a"
waitUntil = "networkidle"

[daummovie_news_recent]
title = "다음영화 뉴스 ─ 최신"
url = "https://movie.daum.net/contents/news?type=recent"
entrySelector = "div.box_movienews ul li"
titleSelector = "strong a[class='link_txt']"
linkSelector = "strong a[class='link_txt']"
imageSelector = "span[class='bg_img']"
contentSelector = "p[class='desc_thumb'] a"
dateSelector = "span.txt_info:nth-child(1)"
dateFormat = "yyyy.MM.dd"
waitUntil = "networkidle"

[daum_entertain_news_drama]
title = "다음 연예 ─ 뉴스 ─ 드라마"
url = "https://entertain.daum.net/news/drama"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "p.desc_thumb"
waitForSelector = "ul.list_news li"
onFail = "stale"
timeout = 180

[daum_entertain_news_variety]
title = "다음 연예 ─ 뉴스 ─ 예능"
url = "https://entertain.daum.net/news/variety"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "p.desc_thumb"
waitForSelector = "ul.list_news li"
onFail = "stale"
timeout = 180

[daum_entertain_news_movie]
title = "다음 연예 ─ 뉴스 ─ 영화"
url = "https://entertain.daum.net/news/movie"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "p.desc_thumb"
waitForSelector = "ul.list_news li"
onFail = "stale"
timeout = 180
