# This is a basic workflow to help you get started with Actions

name: indefinite commits

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings
        with:
          time_elapsed: 3
